### ISSUE TITLE
Nice addition! A few suggestions....

### ISSUE THREAD

**Issue by sarambl** [MetOs-UiO/uio_geo_poster_template#1]
1. Add that additional templates (e.g. in other formates (svg, pptx, tex whatever) is very welcome? I.e. welcome cooperation?
2. Any reason this repo is private? 
3. Can I add a link in https://github.com/MetOs-UiO/info_links_etc ?

**Comment by sunnivin** [comment]
Thank you for the template @ziu1986!

An additional question: 
4. Have you (both @sarambl  and @ziu1986) seen [this](https://no.overleaf.com/latex/templates/uioposter/tsmrpnztthrr) template?

**Comment by ziu1986** [comment]
@sarambl 
Regarding 2: Nope. I just didn't change the github default.
Regarding 1: I don't have any other :D.

@sunnivin
No, but I have seen the official UiO template for the apple version of Powerpoint/Impress. I deemed it as too "black" (on the scale of ink:information ratio). Hence, I shrunk the black part in my template ;-).

**Comment by sarambl** [comment]
@ziu1986 I was actually not suggesting that you add other templates, but I was suggesting adding something like "Please feel free to add other templetes to this repo" to the readme :)

**Comment by sarambl** [comment]
@sunnivin Nope, I had not! looks nice though. Very similar to the one I use (svg) which I inherited from someone else...(I use inkscape, which I am not sure I will recommend...)

**Comment by ziu1986** [comment]
@sarambl Please feel free to add it to the "links". You are welcome to upload your inkscape template as well!
@sunnivin I would not recommend latex for anything with more than ONE picture per box!

**Comment by sunnivin** [comment]
Nice work, 

I think we can close the issue now.
